---
# Some comment
- name: Install virtualisation host
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Include role install_virthost from collection zilux.tools
      ansible.builtin.include_role:
        name: zilux.tools.install_virthost